# -*- coding: utf-8 -*-
"""Friends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwk3JfnwILg90neoW-DPxl_kyDv4saSC
"""

import kagglehub
import os
import re
import pandas as pd

# Dataset depuis Kaggle (voir site)
path = kagglehub.dataset_download("blessondensil294/friends-tv-series-screenplay-script")
print("Path to dataset files:", path)

#Créer un path
dataset_path = path
print("Liste des fichiers :", os.listdir(dataset_path))

# Dataframe vide
mainData = pd.DataFrame(columns=['season', 'episode', 'character', 'line'])

# Traitement des fichiers
for filename in os.listdir(dataset_path):
    if filename.endswith(".txt"):  # Vérifier que c'est un fichier texte
        season = re.findall(r"([sS][0-9]{2})E[0-9]{2}", filename)
        episode = re.findall(r"[sS][0-9]{2}(E[0-9]{2})", filename)

        if season and episode:  # Vérifier qu'on a trouvé une saison et un épisode
            season = season[0].upper()
            episode = episode[0].upper()

            # Script
            script_path = os.path.join(dataset_path, filename)
            with open(script_path, "r", encoding="utf-8") as file:
                lines = file.readlines()

            for line in lines:
                character_match = re.match(r"^(Monica|Rachel|Joey|Chandler|Ross|Phoebe):", line)
                if character_match:
                    character = character_match.group(1)  # Nom du personnage
                    cleanLine = line.replace(character + ":", "").strip()  # Nettoyer la réplique

                    # Ajouter ligne dataframe
                    newRow = pd.DataFrame([{'season': season, 'episode': episode, 'character': character, 'line': cleanLine}])
                    mainData = pd.concat([mainData, newRow], ignore_index=True)

# Création d'un CSV pour le projet
output_folder = "/mnt/data"  #Zone csv (google collab) que j'ai ensuite download
os.makedirs(output_folder, exist_ok=True)
output_csv = os.path.join(output_folder, "friends_dialogues.csv")
mainData.to_csv(output_csv, index=False)

print(f"Fichier CSV enregistré ici : {output_csv}")